
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nevbarpage from './nevbar/nevbar'
import Footer from './footer/footer'
import bcImage from '@/app/images/FLASHMEUP-63.jpg'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Varnya',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} > <main className='bodyContainer'>{children}<Nevbarpage/><Footer /></main></body>
      
    </html>
  )
}
